// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyAdmin.QuotesMS.API.Data;

namespace PolicyAdmin.QuotesMS.API.Migrations
{
    [DbContext(typeof(QuotesContext))]
    [Migration("20210802013056_Populate_Quotes_Data")]
    partial class Populate_Quotes_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyAdmin.QuotesMS.API.Models.QuoteMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinesssValueRangeFrom")
                        .HasColumnType("int");

                    b.Property<int>("BusinesssValueRangeTo")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("PropertyValueRangeFrom")
                        .HasColumnType("int");

                    b.Property<int>("PropertyValueRangeTo")
                        .HasColumnType("int");

                    b.Property<int>("Quote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuotesMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
